version: "3"

services:
  reverse_proxy:
    image: caddy:2.9.1-alpine
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    restart: always

networks:
  - caddy_reverse_proxy
